# .streamlit/secrets.toml

# Credentials for the app's login page
[credentials]
usernames = ["dam", "pi_user"]
passwords = ["dam_admin2025", "pi_user2025"]

# SolarEdge API configuration
[solaredge]
api_key = "RQV3CFF6ZJZSQ671FSY09GVVT2AVWFUK"